### ISSUE TITLE
No conversions Module being installed from npm i 'lib name'

### ISSUE THREAD

**Issue by shivardev** [Cardoso222/cr3-to-jpg#1]
while installing the library with
```
npm install cr3-to-jpg
```
![image](https://github.com/Cardoso222/cr3-to-jpg/assets/38292566/11e62d02-c281-4d95-8ae4-08ab4e4b9da3)

The coversors part of the code is not being installed.

![image](https://github.com/Cardoso222/cr3-to-jpg/assets/38292566/b28f3ecb-165e-466f-9c7a-94e40448a0b8)

I hope you fix this soon! so that I can use this wonderful lib. Thank you

**Comment by Cardoso222** [comment]
Fixed on v1.0.7! 
Thank you for the report!
